language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
install:
    - "pip install --upgrade pip"
    - "pip install -r requirements.txt"
    - "pip install coveralls"
script:
    - "./tests.sh"
after_success:
    - coveralls
